
#{% set data = load_setup_py_data() %}

package:
  name: epidope
  version: 0.2

source:
  path: ../

build:
  number: 33
  noarch: python
#  script: python setup.py install --single-version-externally-managed --record=record.txt
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - tensorflow <1.14
    - bokeh <2
    - numpy
    - scikit-learn <0.23
    - keras <3
    - pytorch
    - libwebp
    - h5py <3
    - allennlp =0.7.2
    - mkl-service


about:
  home: https://github.com/flomock/EpiDope
  summary: Prediction of B-cell epitopes from amino acid sequences using deep neural networks. 
  license: MIT
  license_file: LICENSE
